apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  selector:
    matchLabels:
      app: product-service
  replicas: 2
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: ibrahimdocker/demo-app:latest
        ports:
        - containerPort: 8080
